package Vistas;
import ArrayLists.AProvInterno;
import ArrayLists.AProvExterno;
import LinkedLists.ProvInternoList;
import modelo.ProvInterno;
import modelo.ProvExterno;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author User
 */
public class RegistroProveedores extends javax.swing.JFrame {
    DefaultTableModel tinterno;
    ProvInternoList intList;
    
    DefaultTableModel texterno = new DefaultTableModel();
    AProvExterno capea = new AProvExterno();
    
    
    public RegistroProveedores() {
        initComponents();
        setLocationRelativeTo(null);
        tinterno=new DefaultTableModel();
        tinterno.addColumn("Nombre");
        tinterno.addColumn("DNI");
        tinterno.addColumn("Area");
        tinterno.addColumn("Sueldo");
        tblinternaPrincipal.setModel(tinterno);
        intList= new ProvInternoList();
        
        texterno.addColumn("Nombre Empresa");
        texterno.addColumn("RUC");
        texterno.addColumn("Telèfono");
        texterno.addColumn("Direcciòn");
        texterno.addColumn("Correo");
        texterno.addColumn("Año de colaboraciòn");
        texterno.addColumn("Gerente General");
        texterno.addColumn("Demora");
        tblExternaPrincipal.setModel(texterno);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombreIN = new javax.swing.JTextField();
        BTNagregarIN = new javax.swing.JButton();
        botonLimIN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinternaPrincipal = new javax.swing.JTable();
        btnEliminarIN = new javax.swing.JButton();
        txtDNIin = new javax.swing.JTextField();
        CMBarea = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        volverIN = new javax.swing.JButton();
        volverIN1 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TXTruc = new javax.swing.JTextField();
        TXTdirec = new javax.swing.JTextField();
        TXTcorreo = new javax.swing.JTextField();
        BTNguardarEX = new javax.swing.JButton();
        botonLimProv = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblExternaPrincipal = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        TXTencar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        TXTtelefono = new javax.swing.JTextField();
        TXTnomEX = new javax.swing.JTextField();
        TXTbuRUC = new javax.swing.JTextField();
        TXTañoEX = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnEliminarEX = new javax.swing.JButton();
        btnOrdenDniMejorado1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel15.setBackground(new java.awt.Color(238, 238, 238));

        jPanel16.setBackground(new java.awt.Color(255, 102, 102));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("REGISTROS DE PROVEEDORES INTERNOS");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Nombre del encargado :");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel12.setText("DNI :");

        txtNombreIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreINActionPerformed(evt);
            }
        });

        BTNagregarIN.setBackground(new java.awt.Color(255, 102, 102));
        BTNagregarIN.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BTNagregarIN.setForeground(new java.awt.Color(255, 255, 255));
        BTNagregarIN.setText("Agregar");
        BTNagregarIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNagregarINActionPerformed(evt);
            }
        });

        botonLimIN.setBackground(new java.awt.Color(102, 102, 102));
        botonLimIN.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        botonLimIN.setForeground(new java.awt.Color(255, 255, 255));
        botonLimIN.setText("Limpiar");
        botonLimIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimINActionPerformed(evt);
            }
        });

        tblinternaPrincipal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tblinternaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "DNI", "Area", "Sueldo"
            }
        ));
        jScrollPane1.setViewportView(tblinternaPrincipal);

        btnEliminarIN.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminarIN.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnEliminarIN.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarIN.setText("Eliminar");
        btnEliminarIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarINActionPerformed(evt);
            }
        });

        txtDNIin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIinActionPerformed(evt);
            }
        });
        txtDNIin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDNIinKeyTyped(evt);
            }
        });

        CMBarea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar--", "Dirección", "Recursos Humanos", "Finanzas", "Marketing", "Tecnología" }));
        CMBarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMBareaActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel23.setText("Area:");

        volverIN.setBackground(new java.awt.Color(255, 102, 102));
        volverIN.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        volverIN.setForeground(new java.awt.Color(255, 255, 255));
        volverIN.setText("Volver");
        volverIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverINActionPerformed(evt);
            }
        });

        volverIN1.setBackground(new java.awt.Color(255, 102, 102));
        volverIN1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        volverIN1.setForeground(new java.awt.Color(255, 255, 255));
        volverIN1.setText("Mostrar Elementos");
        volverIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverIN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(BTNagregarIN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(volverIN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarIN, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonLimIN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8)
                                .addComponent(txtNombreIN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142)
                                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDNIin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel15Layout.createSequentialGroup()
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CMBarea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(volverIN1))
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNombreIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtDNIin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CMBarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(12, 12, 12)
                .addComponent(volverIN1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTNagregarIN)
                        .addComponent(btnEliminarIN)
                        .addComponent(volverIN))
                    .addComponent(botonLimIN))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Prov. Interno", jPanel14);

        jPanel18.setBackground(new java.awt.Color(238, 238, 238));

        jPanel19.setBackground(new java.awt.Color(255, 102, 102));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("REGISTROS DE PROVEEDORES EXTERNOS");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel14.setText("RUC de la empresa:");

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setText("Dirección de la empresa");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel16.setText("Correo:");

        jLabel17.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel17.setText("Nombre de la empresa:");

        TXTruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTrucKeyTyped(evt);
            }
        });

        TXTdirec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTdirecKeyTyped(evt);
            }
        });

        TXTcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTcorreoKeyTyped(evt);
            }
        });

        BTNguardarEX.setBackground(new java.awt.Color(255, 102, 102));
        BTNguardarEX.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BTNguardarEX.setForeground(new java.awt.Color(255, 255, 255));
        BTNguardarEX.setText("Agregar");
        BTNguardarEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNguardarEXActionPerformed(evt);
            }
        });

        botonLimProv.setBackground(new java.awt.Color(102, 102, 102));
        botonLimProv.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        botonLimProv.setForeground(new java.awt.Color(255, 255, 255));
        botonLimProv.setText("Limpiar");
        botonLimProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimProvActionPerformed(evt);
            }
        });

        tblExternaPrincipal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tblExternaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "RUC", "Año", "Telefono", "Correo", "Direccion", "Encargado", "Demora"
            }
        ));
        jScrollPane2.setViewportView(tblExternaPrincipal);

        btnVolver.setBackground(new java.awt.Color(102, 102, 102));
        btnVolver.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Buscar.Telf");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel18.setText("Gerente General:");

        TXTencar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTencarKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel19.setText("Telefono de la empresa:");

        jLabel20.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel20.setText("Año de colaboración:");

        TXTtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTtelefonoKeyTyped(evt);
            }
        });

        TXTnomEX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTnomEXKeyTyped(evt);
            }
        });

        TXTbuRUC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTbuRUCKeyTyped(evt);
            }
        });

        TXTañoEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTañoEXActionPerformed(evt);
            }
        });
        TXTañoEX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXTañoEXKeyTyped(evt);
            }
        });

        jButton1.setText("BUSCAR RUC EMPRESA ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnEliminarEX.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminarEX.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnEliminarEX.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEX.setText("Eliminar");
        btnEliminarEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEXActionPerformed(evt);
            }
        });

        btnOrdenDniMejorado1.setBackground(new java.awt.Color(255, 102, 102));
        btnOrdenDniMejorado1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnOrdenDniMejorado1.setForeground(new java.awt.Color(255, 255, 255));
        btnOrdenDniMejorado1.setText("Or.RUC");
        btnOrdenDniMejorado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenDniMejorado1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel18))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TXTruc)
                                        .addComponent(TXTdirec)
                                        .addComponent(TXTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TXTencar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TXTbuRUC, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                                    .addGroup(jPanel18Layout.createSequentialGroup()
                                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TXTañoEX)
                                            .addComponent(TXTnomEX)
                                            .addComponent(TXTtelefono)))))
                            .addGroup(jPanel18Layout.createSequentialGroup()
                                .addComponent(BTNguardarEX, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarEX, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnOrdenDniMejorado1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonLimProv, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(TXTruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTnomEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TXTdirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))))
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(TXTcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(TXTañoEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TXTencar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXTbuRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(71, 71, 71)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(jButton3)
                    .addComponent(BTNguardarEX)
                    .addComponent(botonLimProv)
                    .addComponent(btnEliminarEX)
                    .addComponent(btnOrdenDniMejorado1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("Prov.Externo", jPanel17);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreINActionPerformed

    private void botonLimINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimINActionPerformed
        // TODO add your handling code here:
        txtDNIin.setText("");
        txtNombreIN.setText("");
        txtDNIin.setText("");
        CMBarea.setSelectedIndex(0);

    }//GEN-LAST:event_botonLimINActionPerformed

    private void txtDNIinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIinActionPerformed

    private void CMBareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMBareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CMBareaActionPerformed

    private void BTNguardarEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNguardarEXActionPerformed
        // TODO add your handling code here:
        long ruc=0L;
        int anio=0;
        int tele=0;
        boolean datosValidos = true;

         if(TXTnomEX.getText().trim().isEmpty() || TXTruc.getText().trim().trim().isEmpty()|| TXTañoEX.getText().trim().isEmpty()|| TXTtelefono.getText().trim().isEmpty()|| TXTcorreo.getText().trim().isEmpty()|| TXTdirec.getText().trim().isEmpty()|| TXTencar.getText().trim().isEmpty())     {
            JOptionPane.showMessageDialog(null, "Complete los campos");
            datosValidos = false;}
         else{

            String nom = TXTnomEX.getText();
            if (!validarLetras(TXTnomEX.getText()))
            {JOptionPane.showMessageDialog(null, "Error al ingresar dato NOMBRE DE LA EMPRESA");
                datosValidos = false;}

            String enca = TXTencar.getText();
            if (!validarLetras(TXTencar.getText()))
            {JOptionPane.showMessageDialog(null, "Error al ingresar dato NOMBRE DEL ENCARGADO");
                datosValidos = false;}

            try {
                ruc = Long.parseLong(TXTruc.getText());
                if (String.valueOf(ruc).length() != 11) {
                    JOptionPane.showMessageDialog(null, "El RUC debe tener 11 dígitos");
                    datosValidos = false; // Marcar los datos como no válidos
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un número válido para el RUC");
                datosValidos = false; // Marcar los datos como no válidos
            }

            try {
                tele = Integer.parseInt(TXTtelefono.getText());
                if (String.valueOf(tele).length() != 9) {
                    JOptionPane.showMessageDialog(null, "El teléfono debe tener 9 dígitos");
                    datosValidos = false; // Marcar los datos como no válidos
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un número válido para el teléfono");
                datosValidos = false;}

            try {
                anio = Integer.parseInt(TXTañoEX.getText());
                if (String.valueOf(anio).length() > 2) {
                    JOptionPane.showMessageDialog(null, "El año debe tener 2 dígitos");
                    datosValidos = false; // Marcar los datos como no válidos
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un número válido para el año");
                datosValidos = false; }

            String cor = TXTcorreo.getText();
            String dir = TXTdirec.getText();
            //Creacion del objeto en un array para la tabla
            ProvExterno ca= new ProvExterno (anio);
            String demo=ca.tiempoProvedor();
            if (datosValidos) {
            texterno.setRowCount(0);
            ProvExterno cape= new ProvExterno(ruc, dir, tele, cor, enca, anio, demo, nom);
            capea.agregarProvExt(cape);
            for (int i = 0; i < capea.tamañoArreglo(); i++) {
                 Object[] fila={
            capea.obtener(i).getNombreProveedor(),
            capea.obtener(i).getRUC(),
            capea.obtener(i).getTelefono(),
            capea.obtener(i).getDireccion(),
            capea.obtener(i).getCorreo(),
            capea.obtener(i).getAñoIngreso(),
            capea.obtener(i).getEncargado(),
            capea.obtener(i).getDemo()
               };
            texterno.addRow(fila);
            }tblExternaPrincipal.setModel(texterno);
            }
        }
    }//GEN-LAST:event_BTNguardarEXActionPerformed
    public static boolean validarLetras(String datos){
        return datos.matches("[a-zA-Z .]*");
     }
        
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        
     
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int telfbusq=Integer.parseInt(JOptionPane.showInputDialog("Ingrese telefono :"));
        
        capea.ordenarProPorTelf();
        
        if (capea.busquedaB(telfbusq)!=null) {
            JOptionPane.showMessageDialog(rootPane,"Nom: "+capea.busquedaB(telfbusq).getNombreProveedor()+
                    " Ruc: "+ capea.busquedaB(telfbusq).getRUC()+" Direccion"+capea.busquedaB(telfbusq).getDireccion());
        }else{
            JOptionPane.showMessageDialog(rootPane, "Telefono no existe...");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        long RUCbus;
        RUCbus=Long.parseLong(TXTbuRUC.getText());
        ProvExterno refc=capea.busquedaS(RUCbus);
        if (refc!=null) {
            JOptionPane.showMessageDialog(rootPane, "RUC:"+refc.getRUC()+"\t Nombre: "+refc.getNombreProveedor()+"\t Telefono: "+refc.getTelefono());
        }else{
            JOptionPane.showMessageDialog(rootPane, "No existe RUC");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonLimProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimProvActionPerformed
        // TODO add your handling code here:
         TXTnomEX.setText("");
        TXTruc.setText("");
        TXTañoEX.setText("");
        TXTtelefono.setText("");
        TXTdirec.setText("");
        TXTcorreo.setText("");
        TXTencar.setText("");
    }//GEN-LAST:event_botonLimProvActionPerformed

    private void TXTañoEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTañoEXActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXTañoEXActionPerformed

    private void TXTrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTrucKeyTyped
        // TODO add your handling code here:
        if (TXTruc.getText().length()>=11)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TXTrucKeyTyped

    private void TXTdirecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTdirecKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTdirecKeyTyped

    private void TXTcorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTcorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTcorreoKeyTyped

    private void TXTencarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTencarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTencarKeyTyped

    private void TXTnomEXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTnomEXKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTnomEXKeyTyped

    private void TXTtelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTtelefonoKeyTyped
        // TODO add your handling code here:
        if (TXTtelefono.getText().length()>=9)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TXTtelefonoKeyTyped

    private void TXTañoEXKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTañoEXKeyTyped
        // TODO add your handling code here:
         if (TXTañoEX.getText().length()>=2)
        {
            evt.consume();
        }
    }//GEN-LAST:event_TXTañoEXKeyTyped

    private void TXTbuRUCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXTbuRUCKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTbuRUCKeyTyped

    private void volverINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverINActionPerformed
        
    }//GEN-LAST:event_volverINActionPerformed

    private void BTNagregarINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNagregarINActionPerformed
        int dni = 0;
        int anio = 0;
        boolean datosValidos = true;

        if (txtDNIin.getText().trim().isEmpty() || txtNombreIN.getText().trim().trim().isEmpty() || CMBarea.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Complete los campos");
            datosValidos = false;
        } else {
            String nom = txtNombreIN.getText();
            if (!validarLetras(txtNombreIN.getText())) {
                JOptionPane.showMessageDialog(null, "Error al ingresar dato NOMBRE");
                datosValidos = false;
            }

            String area = CMBarea.getSelectedItem().toString();

            try {
                dni = Integer.parseInt(txtDNIin.getText());
                if (String.valueOf(dni).length() != 8) {
                    JOptionPane.showMessageDialog(null, "El DNI debe tener 8 dígitos");
                    datosValidos = false; // Marcar los datos como no válidos
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese un número válido para el DNI");
                datosValidos = false; // Marcar los datos como no válidos
            }
            ProvInterno insa = new ProvInterno(area);
            double suel = insa.calcsueldo(area);
            // Creacion del objeto en un array para la tabla
            if (datosValidos) {
                
                ProvInterno pint = new ProvInterno(area, dni, suel, nom);
                intList.insertarCola(pint);
                Object[] rowData={
                    pint.getNombreProveedor(),
                    pint.getDni(),
                    pint.getArea(),
                    pint.getSuel(),
                };
                tinterno.addRow(rowData);
            }
        }
    }//GEN-LAST:event_BTNagregarINActionPerformed

    private void txtDNIinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIinKeyTyped
        // TODO add your handling code here:
        if (txtDNIin.getText().length()>=8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtDNIinKeyTyped

    private void btnEliminarINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarINActionPerformed
        if (tinterno.getRowCount()>0) {
            tinterno.removeRow(0);
            intList.QuitardelaCola();
        }else
            JOptionPane.showMessageDialog(null, "Cola Vacia");
        
        
    }//GEN-LAST:event_btnEliminarINActionPerformed

    private void btnEliminarEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEXActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tblExternaPrincipal.getSelectedRow();
        if (filaSeleccionada >= 0) {
            // Elimina la fila seleccionada del modelo de tabla Higiene
            texterno.removeRow(filaSeleccionada);
            capea.eliminarProvExt(filaSeleccionada);
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila para eliminar.");
        }              
    }//GEN-LAST:event_btnEliminarEXActionPerformed

    private void btnOrdenDniMejorado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenDniMejorado1ActionPerformed
        texterno.setRowCount(0);
        capea.ordenarRucBurbujaMejorado();
        for (int i = 0; i < capea.tamañoArreglo(); i++) {
                 Object[] fila={
            capea.obtener(i).getNombreProveedor(),
            capea.obtener(i).getRUC(),
            capea.obtener(i).getTelefono(),
            capea.obtener(i).getDireccion(),
            capea.obtener(i).getCorreo(),
            capea.obtener(i).getAñoIngreso(),
            capea.obtener(i).getEncargado(),
            capea.obtener(i).getDemo()
               };
            texterno.addRow(fila);
            }tblExternaPrincipal.setModel(texterno);
            
    }//GEN-LAST:event_btnOrdenDniMejorado1ActionPerformed

    private void volverIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverIN1ActionPerformed
        intList.mostar();
    }//GEN-LAST:event_volverIN1ActionPerformed
    public boolean verificar_email(String correo){
        Pattern patron = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
        +"[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{3,})$");
        Matcher mat = patron.matcher(correo);
        return mat.find();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroProveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNagregarIN;
    private javax.swing.JButton BTNguardarEX;
    private javax.swing.JComboBox<String> CMBarea;
    private javax.swing.JTextField TXTañoEX;
    private javax.swing.JTextField TXTbuRUC;
    private javax.swing.JTextField TXTcorreo;
    private javax.swing.JTextField TXTdirec;
    private javax.swing.JTextField TXTencar;
    private javax.swing.JTextField TXTnomEX;
    private javax.swing.JTextField TXTruc;
    private javax.swing.JTextField TXTtelefono;
    private javax.swing.JButton botonLimIN;
    private javax.swing.JButton botonLimProv;
    private javax.swing.JButton btnEliminarEX;
    private javax.swing.JButton btnEliminarIN;
    private javax.swing.JButton btnOrdenDniMejorado1;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable tblExternaPrincipal;
    private javax.swing.JTable tblinternaPrincipal;
    private javax.swing.JTextField txtDNIin;
    private javax.swing.JTextField txtNombreIN;
    private javax.swing.JButton volverIN;
    private javax.swing.JButton volverIN1;
    // End of variables declaration//GEN-END:variables
}
